### ISSUE TITLE
in version 1.0.2 half of lights unreachable

### ISSUE THREAD

**Issue by nattlip** [athombv/nl.philips.hue#14]
after rebooting reinstalling hue . i put all lamps on ( with hue android app so that homey can see tem )
![knipsel](https://cloud.githubusercontent.com/assets/7040452/15870284/0c456e04-2cf0-11e6-868e-1ff91d5164fe.PNG)

**Comment by Fire69** [comment]
I had this problem also.
First the lights would have the onoff:invalid_type error.
After a reboot or disable/enable they would ALL become unreachable.
I removed everything again, and only added the ones I know are actually reachable (I have lights behind normal switches)
This solved it for me.

@nattlip: is it possible your LIvingwhites 4 (I guess it's 4 after 3 :) ) is unreachable? Because that's where the problem starts?
My first light (lowest ID in the Hue app) is unreachable, I think that's why all the following are shown unreachable too.

**Comment by cnvisser** [comment]
I had the same problem as @nattlip 
After removing the lights and adding them i got the error on all the lights
![image](https://cloud.githubusercontent.com/assets/18187379/15885467/a6c9ff5a-2d57-11e6-814a-32301ebc4cd7.png)

**Comment by Fire69** [comment]
@cnvisser: go to Settings - Apps and disable/enable the Hue app.
After that it will either work, or they will all/partially become unreachable.

**Comment by cnvisser** [comment]
@Fire69 Thank u very much that worked. All 20 lights working again.

**Comment by nattlip** [comment]
today a removed the new 1.0.2 hue app . cold reboot homey and installing the app again and added the app as a user. . all lamps were reavhabel but all lamps geve invalid type errors so cold reboot homey again. and the lights were reachable and and coulb be controlled at the device page but after 5 minutes half of the lights becem unreachable again. All lamps were online and on , philips hue android app sees them all reachable.

**Comment by sossienl** [comment]
Same problem here. Not reachable. Also not after disabling & enabling the app

**Comment by Deentje** [comment]
I have the same problem but only on my living white plugs

**Comment by WeeJeWel** [comment]
Try again in 1.0.4

**Comment by nattlip** [comment]
@WeeJeWel : indeed runs perfect everything works now , also the plugs etc. 1.0.5
