### ISSUE TITLE
Set random color

### ISSUE THREAD

**Issue by Fire69** [athombv/nl.philips.hue#20]
Could you please add an action card for setting a random color?

**Comment by WeeJeWel** [comment]
I was thinking about this. It could change the hue, brightness and
saturation, which together make a color.

I think only changing the hue would be best, while saturation will be set
to 1 (full color).

Any opinions?

On Jul 17, 2016 16:11, "Fire69" <notifications@github.com> wrote:

Could you please add an action card for setting a random color?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/nl.philips.hue/issues/20>, or mute the thread

**Comment by Fire69** [comment]
Yes, saturation at 1 and random hue would be ok I guess. 
I already set the brightness in my flow before picking a color.

**Comment by jeroenbos22** [comment]
I would love to have this!

**Comment by jeroenbos22** [comment]
@WeeJeWel That is the way to go. Have a php script where I do the same. First I had everything random (also sat, bri) but that gave a lot of half (white-ish) colors.

**Comment by WeeJeWel** [comment]
Fixed in the current git version (thanks @jordenc!)
