### ISSUE TITLE
Change a lamp color / brightness in a flow is not working as expected

### ISSUE THREAD

**Issue by sossienl** [athombv/nl.philips.hue#32]
1. Some hex colors are not translated to a corresponding HUE color, meaning the lamp will not change color.
2. When setting the brightness it will not use the color it currently has,  but will use the color under "change to color".

Besides this from a UX perspective; When trying to set a color for a lamp, from a flow, it's almost impossible to do so. A very small color picker and no way to enter a HEX manually.

**Comment by caseda** [comment]
1. Do you pres [OK] after changing color? or just click away

2. how is that even possible? the card only triggers the one that is showing, you must have another card in the same flow that changes the colour

![screenie](https://cloud.githubusercontent.com/assets/2565450/20169971/9c8a2d60-a72a-11e6-93a0-dc98bd96cf14.jpg)

manual hex is definitely possible

**Comment by sossienl** [comment]
1. Yes
2. Got it, so that is indeed possible.

**Comment by caseda** [comment]
ah, i think i know what you mean with point 1, that is something lacking in the hue lights and not really the responsibility of homey

then they would need 3 different hue selectors just because hue lights can't represent the color "green" fully.
2 just for hue, since there is a difference between bulbs/gu10 and led strips, and the one left for the rest, that probably also are different by a little bit

**Comment by WeeJeWel** [comment]
So this is working? I'm closing this issue.
