### ISSUE TITLE
Activating lights via Voice: "Ik Kon geen lampen vinden om aan te zetten"

### ISSUE THREAD

**Issue by sossienl** [athombv/nl.philips.hue#38]
Every time I activate Homey via voice to turn on my lights in the living room, starts with "Ik Kon geen lampen vinden om aan te zetten", shortly after the lamps are turned on.

**Comment by sossienl** [comment]
Also when turning  the lights off

**Comment by Tweake** [comment]
That's interesting, would you be willing to provide a few more details so I can try to reproduce the issue here? Specifically: 
- the exact phrase you said to Homey (from [Homey-ip-address]/manager/speech-input)
- screenshot(s) showing your devices screen, so I can see in which zones all your lights are (not just the Philips Hues)
- A list of lights which you are using with Homey, brand and type

**Comment by CharleyDoe** [comment]
Same problem here!
3 zones 13 lambs 
Voice command "zet de lichten uit"/"zet de lichten aan" "zet de lampen uit"/"zet de lampen aan"
Homey firmware 1.01 Hue 2.1.0

**Comment by sossienl** [comment]
My info:

**The flow with the phrase I'm saying:**
<img width="963" alt="screen shot 2016-11-22 at 22 24 13" src="https://cloud.githubusercontent.com/assets/609650/20542573/6ffc4e22-b102-11e6-88ba-ae8d8f7d7b1b.png">

**Overview of my devices. But they are in different rooms. Do you need all of them? I have for instance 10 Hue lights outside (garden):**

<img width="1244" alt="screen shot 2016-11-22 at 22 25 03" src="https://cloud.githubusercontent.com/assets/609650/20542612/a707a600-b102-11e6-857c-ef9b38da43a8.png">


I have over 20 lights, All are Philips HUE. Most of them are GU10,  3 of them are E27

**Comment by CharleyDoe** [comment]
Without a flow homey responds to the command "turn the lights on" and respond with "I can not find any lights". With a hue flow enabled to turn on/off the lights, lights does go on or off and homey respond after that I can not find any lights..

**Comment by Tweake** [comment]
Thanks for the useful info and screenshots! This is enough information to understand what is causing your issue.

When you say "lampen woonkamer aan" Homey will respond with two messages: "Ik kon geen lampen vinden om aan te zetten" and your own flow's "lampen in je woonkamer staan aan". This is happening because Homey as built-in voice commands to control your lights, which respond to phrases that contain the words "lampen" and "aan"(among other things). However, the flow you have created overlaps with the built-in commands, which is why you are hearing both.

Now for the reason why Homey is saying there were no lights found, which is an interesting case. Homey checks if you have mentioned any devices by name, and then only looks at those devices since you specifically referred to them. You are saying the name of your Fibaro sensor "Woonkamer", which is not a light. So Homey could not find any lights because it only looked at your "Woonkamer" sensor.

**To solve your issue:**
It's generally a bad idea to have voice triggers in flows which overlap with Homey's built-in flow. You can change your voice trigger to something like "maak de woonkamer gezellig" to make sure the conflict no longer occurs.

Alternatively, you can try using the built-in speech commands. If you rename the zone "Living Room" to "Woonkamer" (by selecting the zone and clicking on the name) or any other Dutch word(s) for that matter, you can use voice to control your lamps in multiple ways. [Some examples can be found here](https://www.athom.com/nl/support/KB000037/), just make sure you don't have any devices with the same name as the zone.

I hope this helps!


P.S. We have plans for making sure a conflict between built-in and flow voice commands cannot happen, but this will not yet be finished in the near future.

**Comment by CharleyDoe** [comment]
Thanks for the detailed instructions, it works now!
