### ISSUE TITLE
Brightness over time broken

### ISSUE THREAD

**Issue by markaswift** [athombv/nl.philips.hue#64]
It appears the change brightness over time card is broken in the latest release. It ignores the period and just actions the set point immediately.

**Comment by Bastios** [comment]
I noticed this as well. For format sake:

What is your Homey version (Settings → System)?

1.1.9

Philips HUE app version is 2.2.3

What did you try to achieve?
Wake up light emulation. I want my bedroom light to  get from 0% brightness to 100% brightness in a time period of 30 minutes.

Please include detailed steps how we can reproduce the issue
Use the 'change brightness over time card' for one of the Philips HUE lightbulbs in the '...then' lane.
Setting the 'Transition(s)' value has no effect, brightness changes in about 1-2 seconds.

What was the result?
The brightness value given is reached within 1 or 2 seconds instead of the value entered.
What did you expect as result?
I expected the brightness to change over the time period that i entered as a value as it did previously

Any other remarks
I am not sure when this function broke, might have been 2 updates ago. (but maybe even 3)

**Comment by markaswift** [comment]
@WeeJeWel any news on this?
