### ISSUE TITLE
Hue-App Documentation

### ISSUE THREAD

**Issue by CyberSponk** [athombv/nl.philips.hue#68]
I don't know where i can place this question:
Is there a Documentation about the HueApp and the settings on WebInterface and/or iOS-App?

Did not really check how the buttons (see attached File) on a bulb could be handeld. I see that they change the color but how they are to understand? Are these Default-Colors?

![x1](https://cloud.githubusercontent.com/assets/26149030/24187695/70d5e0c6-0ede-11e7-83db-fd9c3051bc0b.png)

Also: What are Information on Hue-Tags? See the bulb with Tag called "Hue" with a Number e.g. 0.05. What means this Number?

**Comment by Keverjeroen** [comment]
@CyberSponk , maybe the forum is a better place for these sort of questions. But this Wiki helped me a lot to understand HSV (Hue, Saturation and Value) or KVW (Kleurtoon, Verzadiging, Waarde): https://nl.wikipedia.org/wiki/HSV_(kleurruimte) 

In this figure you can see, what happens if you change one of the HSV settings: https://nl.wikipedia.org/wiki/HSV_(kleurruimte)#/media/File:HSV_cone.jpg

**Comment by WeeJeWel** [comment]
This will be more clear with the new Homey Smartphone App.

Closing because not a Hue-specific issue.
